/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesAdmin;

import java.awt.Color;

/**
 *
 * @author user
 */
public class AdminEditarMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminCrearHabitacion
     */
    public AdminEditarMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        PanelAzul1 = new javax.swing.JPanel();
        PanelAzul2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TextFieldPrecio = new javax.swing.JTextField();
        LabelRutaPrecio = new javax.swing.JLabel();
        LabelNumero = new javax.swing.JLabel();
        TextFieldNumero = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        LabelDescripcion = new javax.swing.JLabel();
        TextFieldDescripcion = new javax.swing.JTextField();
        BotonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAzul1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout PanelAzul1Layout = new javax.swing.GroupLayout(PanelAzul1);
        PanelAzul1.setLayout(PanelAzul1Layout);
        PanelAzul1Layout.setHorizontalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        PanelAzul1Layout.setVerticalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        Fondo.add(PanelAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 400));

        PanelAzul2.setBackground(new java.awt.Color(51, 102, 255));

        Titulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("5. Editar menú del restaurante");

        javax.swing.GroupLayout PanelAzul2Layout = new javax.swing.GroupLayout(PanelAzul2);
        PanelAzul2.setLayout(PanelAzul2Layout);
        PanelAzul2Layout.setHorizontalGroup(
            PanelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Titulo)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        PanelAzul2Layout.setVerticalGroup(
            PanelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Titulo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Fondo.add(PanelAzul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 650, 60));

        TextFieldPrecio.setText("ingrese aca el precio del plato");
        TextFieldPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldPrecioMouseClicked(evt);
            }
        });
        TextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPrecioActionPerformed(evt);
            }
        });
        Fondo.add(TextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        LabelRutaPrecio.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelRutaPrecio.setText("Precio del Plato");
        Fondo.add(LabelRutaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        LabelNumero.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelNumero.setText("Numero del Plato");
        Fondo.add(LabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        TextFieldNumero.setText("ingrese aca el numero del plato");
        TextFieldNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNumeroMouseClicked(evt);
            }
        });
        Fondo.add(TextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        LabelNombre.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelNombre.setText("Nombre del Plato");
        Fondo.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        TextFieldNombre.setText("ingrese aca el nombre del plato\n");
        TextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldNombreMouseClicked(evt);
            }
        });
        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        Fondo.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        LabelDescripcion.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelDescripcion.setText("Descripción del Plato");
        Fondo.add(LabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        TextFieldDescripcion.setText("ingrese aca la descripcion del plato");
        TextFieldDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldDescripcionMouseClicked(evt);
            }
        });
        TextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldDescripcionActionPerformed(evt);
            }
        });
        Fondo.add(TextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        BotonSiguiente.setBackground(new java.awt.Color(51, 102, 255));
        BotonSiguiente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("Añadir");
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseExited(evt);
            }
        });
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        Fondo.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldPrecioMouseClicked
        // TODO add your handling code here:
        TextFieldPrecio.setText("");
    }//GEN-LAST:event_TextFieldPrecioMouseClicked

    private void TextFieldNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNumeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumeroMouseClicked

    private void TextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPrecioActionPerformed

    private void TextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreMouseClicked

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldDescripcionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDescripcionMouseClicked

    private void TextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldDescripcionActionPerformed

    private void BotonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseEntered
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_BotonSiguienteMouseEntered

    private void BotonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseExited
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_BotonSiguienteMouseExited

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelRutaPrecio;
    private javax.swing.JPanel PanelAzul1;
    private javax.swing.JPanel PanelAzul2;
    private javax.swing.JTextField TextFieldDescripcion;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNumero;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
