/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesAdmin;

import java.awt.Color;

/**
 *
 * @author user
 */
public class AdminCargarTarifas extends javax.swing.JFrame {

    /**
     * Creates new form AdminCrearHabitacion
     */
    public AdminCargarTarifas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        PanelAzul1 = new javax.swing.JPanel();
        PanelAzul2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TextFieldFechaFinal = new javax.swing.JTextField();
        TextFieldFechaIncial = new javax.swing.JTextField();
        LabelDias = new javax.swing.JLabel();
        LabelFechaI = new javax.swing.JLabel();
        LabelFechaF = new javax.swing.JLabel();
        LabelTipoCuarto2 = new javax.swing.JLabel();
        RadioButtonLunes = new javax.swing.JRadioButton();
        RadioButtonMartes = new javax.swing.JRadioButton();
        RadioButtonMiercoles = new javax.swing.JRadioButton();
        RadioButtonJueves = new javax.swing.JRadioButton();
        RadioButtonViernes = new javax.swing.JRadioButton();
        RadioButtonSabado = new javax.swing.JRadioButton();
        RadioButtonDomingo = new javax.swing.JRadioButton();
        BotonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAzul1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout PanelAzul1Layout = new javax.swing.GroupLayout(PanelAzul1);
        PanelAzul1.setLayout(PanelAzul1Layout);
        PanelAzul1Layout.setHorizontalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        PanelAzul1Layout.setVerticalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        Fondo.add(PanelAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 400));

        PanelAzul2.setBackground(new java.awt.Color(51, 102, 255));

        Titulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("6. Cargar las tarifas por tipo de cuarto");

        javax.swing.GroupLayout PanelAzul2Layout = new javax.swing.GroupLayout(PanelAzul2);
        PanelAzul2.setLayout(PanelAzul2Layout);
        PanelAzul2Layout.setHorizontalGroup(
            PanelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Titulo)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        PanelAzul2Layout.setVerticalGroup(
            PanelAzul2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Titulo)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Fondo.add(PanelAzul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 650, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de cuarto", "Suite", "Suite Doble", "Estandar" }));
        Fondo.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        TextFieldFechaFinal.setText("AAAA/MM/DD");
        TextFieldFechaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldFechaFinalMouseClicked(evt);
            }
        });
        Fondo.add(TextFieldFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        TextFieldFechaIncial.setText("AAAA/MM/DD");
        TextFieldFechaIncial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldFechaIncialMouseClicked(evt);
            }
        });
        Fondo.add(TextFieldFechaIncial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        LabelDias.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelDias.setText("Dias de la semana");
        Fondo.add(LabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        LabelFechaI.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelFechaI.setText("FECHA INICIAL");
        Fondo.add(LabelFechaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        LabelFechaF.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelFechaF.setText("FECHA FINAL");
        Fondo.add(LabelFechaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        LabelTipoCuarto2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelTipoCuarto2.setText("TIPO DE CUARTO");
        Fondo.add(LabelTipoCuarto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        RadioButtonLunes.setText("Lunes");
        RadioButtonLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonLunesActionPerformed(evt);
            }
        });
        Fondo.add(RadioButtonLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        RadioButtonMartes.setText("Martes");
        Fondo.add(RadioButtonMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        RadioButtonMiercoles.setText("Miercoles");
        RadioButtonMiercoles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RadioButtonMiercolesKeyReleased(evt);
            }
        });
        Fondo.add(RadioButtonMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        RadioButtonJueves.setText("Jueves");
        Fondo.add(RadioButtonJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        RadioButtonViernes.setText("Viernes");
        Fondo.add(RadioButtonViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        RadioButtonSabado.setText("Sabado");
        RadioButtonSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSabadoActionPerformed(evt);
            }
        });
        Fondo.add(RadioButtonSabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        RadioButtonDomingo.setText("Domingo");
        Fondo.add(RadioButtonDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        BotonSiguiente.setBackground(new java.awt.Color(51, 102, 255));
        BotonSiguiente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("Cargar");
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseExited(evt);
            }
        });
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        Fondo.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFechaIncialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldFechaIncialMouseClicked
        // TODO add your handling code here:
        TextFieldFechaIncial.setText("");
    }//GEN-LAST:event_TextFieldFechaIncialMouseClicked

    private void TextFieldFechaFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldFechaFinalMouseClicked
        // TODO add your handling code here:
        TextFieldFechaFinal.setText("");
    }//GEN-LAST:event_TextFieldFechaFinalMouseClicked

    private void RadioButtonLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonLunesActionPerformed

    private void RadioButtonSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonSabadoActionPerformed

    private void RadioButtonMiercolesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RadioButtonMiercolesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonMiercolesKeyReleased

    private void BotonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseEntered
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_BotonSiguienteMouseEntered

    private void BotonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiguienteMouseExited
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(51,102,255));
    }//GEN-LAST:event_BotonSiguienteMouseExited

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCargarTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCargarTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCargarTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCargarTarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCargarTarifas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel LabelDias;
    private javax.swing.JLabel LabelFechaF;
    private javax.swing.JLabel LabelFechaI;
    private javax.swing.JLabel LabelTipoCuarto2;
    private javax.swing.JPanel PanelAzul1;
    private javax.swing.JPanel PanelAzul2;
    private javax.swing.JRadioButton RadioButtonDomingo;
    private javax.swing.JRadioButton RadioButtonJueves;
    private javax.swing.JRadioButton RadioButtonLunes;
    private javax.swing.JRadioButton RadioButtonMartes;
    private javax.swing.JRadioButton RadioButtonMiercoles;
    private javax.swing.JRadioButton RadioButtonSabado;
    private javax.swing.JRadioButton RadioButtonViernes;
    private javax.swing.JTextField TextFieldFechaFinal;
    private javax.swing.JTextField TextFieldFechaIncial;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
