package interfacesRecepcionista;

import java.awt.Color;

import prosecution.RecepcionistProcess;

public class RecepcionistaCancelarReserva extends javax.swing.JFrame {

    /**
     * Creates new form RecepcionistaConsultarHabitacion
     */
    public RecepcionistaCancelarReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        PanelAzul = new javax.swing.JPanel();
        PanelAzul1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID1 = new javax.swing.JLabel();
        TextFieldID1 = new javax.swing.JTextField();
        BotonSiguiente = new javax.swing.JButton();
        LabelNumerPersonas2 = new javax.swing.JLabel();
        LabelNumerPersonas3 = new javax.swing.JLabel();
        LabelNumerPersonas = new javax.swing.JLabel();
        TextFieldAño = new javax.swing.JTextField();
        TextFieldMes = new javax.swing.JTextField();
        TextFieldDia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelAzul.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout PanelAzulLayout = new javax.swing.GroupLayout(PanelAzul);
        PanelAzul.setLayout(PanelAzulLayout);
        PanelAzulLayout.setHorizontalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        PanelAzulLayout.setVerticalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        Fondo.add(PanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 390));

        PanelAzul1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("3. Cancelar Reserva");

        javax.swing.GroupLayout PanelAzul1Layout = new javax.swing.GroupLayout(PanelAzul1);
        PanelAzul1.setLayout(PanelAzul1Layout);
        PanelAzul1Layout.setHorizontalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        PanelAzul1Layout.setVerticalGroup(
            PanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzul1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Fondo.add(PanelAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 630, 80));

        ID1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ID1.setText("ID de Reserva");
        Fondo.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        TextFieldID1.setText("Ingrese aca el ID de la reserva a cancelar");
        TextFieldID1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldID1MouseClicked(evt);
            }
        });
        Fondo.add(TextFieldID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        BotonSiguiente.setBackground(new java.awt.Color(51, 102, 255));
        BotonSiguiente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("SIGUIENTE");
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseExited(evt);
            }
        });
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        Fondo.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        LabelNumerPersonas2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelNumerPersonas2.setText("Año");
        Fondo.add(LabelNumerPersonas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        LabelNumerPersonas3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelNumerPersonas3.setText("Mes");
        Fondo.add(LabelNumerPersonas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        LabelNumerPersonas.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        LabelNumerPersonas.setText("Dia");
        Fondo.add(LabelNumerPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        TextFieldAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAñoActionPerformed(evt);
            }
        });
        Fondo.add(TextFieldAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        TextFieldMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMesActionPerformed(evt);
            }
        });
        Fondo.add(TextFieldMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        Fondo.add(TextFieldDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void TextFieldID1MouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void BotonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(0,0,255));
    }                                           

    private void BotonSiguienteMouseExited(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(51,102,255));
    }                                          

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	String id = TextFieldID1.getText();
    	int ano = Integer.parseInt(LabelNumerPersonas.getText());
        int mes = Integer.parseInt(LabelNumerPersonas2.getText());
        int dia = Integer.parseInt(LabelNumerPersonas3.getText());
        RecepcionistProcess.CancelarReserva(id, dia, mes, ano);
        dispose();

    }                                              

    private void TextFieldAñoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void TextFieldMesActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepcionistaCancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepcionistaCancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepcionistaCancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepcionistaCancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecepcionistaCancelarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel ID1;
    private javax.swing.JLabel LabelNumerPersonas;
    private javax.swing.JLabel LabelNumerPersonas2;
    private javax.swing.JLabel LabelNumerPersonas3;
    private javax.swing.JPanel PanelAzul;
    private javax.swing.JPanel PanelAzul1;
    private javax.swing.JTextField TextFieldAño;
    private javax.swing.JTextField TextFieldDia;
    private javax.swing.JTextField TextFieldID1;
    private javax.swing.JTextField TextFieldMes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}