package interfacesGeneral;

import java.awt.Color;

import prosecution.TransaccionesPasarelas;

/**
 *
 * @author user
 */
public class Pagotarjeta extends javax.swing.JFrame {

    /**
     * Creates new form LoginInterfaz
     */
    public Pagotarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelAzul = new javax.swing.JPanel();
        LabelIniciarSesion = new javax.swing.JLabel();
        PanelGris = new javax.swing.JPanel();
        LabelHotelDpoo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        BotonSiguiente = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Numerotarjeta = new javax.swing.JTextField();
        Monto = new javax.swing.JTextField();
        labelUsuario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAzul.setBackground(new java.awt.Color(51, 102, 255));

        LabelIniciarSesion.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        LabelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        LabelIniciarSesion.setText("Gracias por pagar");

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(LabelIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAzulLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(LabelIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );

        background.add(panelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 400));

        LabelHotelDpoo.setFont(new java.awt.Font("DIN Condensed", 1, 48)); // NOI18N
        LabelHotelDpoo.setText("Pago Electronico");

        javax.swing.GroupLayout PanelGrisLayout = new javax.swing.GroupLayout(PanelGris);
        PanelGris.setLayout(PanelGrisLayout);
        PanelGrisLayout.setHorizontalGroup(
            PanelGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGrisLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(LabelHotelDpoo)
                .addGap(105, 105, 105))
        );
        PanelGrisLayout.setVerticalGroup(
            PanelGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGrisLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelHotelDpoo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        background.add(PanelGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 470, 90));

        labelUsuario.setText("Monto");
        background.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        LabelContraseña.setText("Numero de tarjeta");
        background.add(LabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, 20));

        BotonSiguiente.setBackground(new java.awt.Color(51, 102, 255));
        BotonSiguiente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BotonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BotonSiguiente.setText("SIGUIENTE");
        BotonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiguienteMouseExited(evt);
            }
        });
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        background.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plataforma", "Payu", "Paypal", "Sire" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        background.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        Numerotarjeta.setText("xxxx xxxx xxxx\n");
        Numerotarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumerotarjetaMouseClicked(evt);
            }
        });
        Numerotarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerotarjetaActionPerformed(evt);
            }
        });
        background.add(Numerotarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        Monto.setText("monto a pagar");
        Monto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MontoMouseClicked(evt);
            }
        });
        Monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoActionPerformed(evt);
            }
        });
        background.add(Monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        labelUsuario1.setText("PLATAFORMA A PAGAR");
        background.add(labelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	String umero_tarjeta=Numerotarjeta.getText();
    	int numero_tarjeta=Integer.parseInt(umero_tarjeta);
    	String pasarela=jComboBox1.getSelectedItem().toString();
    	String onto=Monto.getText();
    	int monto=Integer.parseInt(onto);
    	
    	TransaccionesPasarelas pago =new TransaccionesPasarelas();
    	pago.Transaccion(pasarela, monto, numero_tarjeta);
    	dispose();
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exitosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exitosa().setVisible(true);
            }
        });
    }                                              

    private void BotonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(0,0,255));
    }                                           

    private void BotonSiguienteMouseExited(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        BotonSiguiente.setBackground(new Color(51,102,255));
    }                                          

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NumerotarjetaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void NumerotarjetaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Numerotarjeta.setText("");
    }                                          

    private void MontoMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    	Monto.setText("");
    }                                  

    private void MontoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelHotelDpoo;
    private javax.swing.JLabel LabelIniciarSesion;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField Numerotarjeta;
    private javax.swing.JPanel PanelGris;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JPanel panelAzul;
    // End of variables declaration                   
}
